service:
  name: rayllm-head-svc
  externalPort: 8000
ingress:
  hosts:
    - ${RAYLLM_HEAD_SVC_INGRESS_HOST}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"